title: retroswan
email: world5ziggurat@gmal.com
description: >- # this means to ignore newlines until "baseurl:"
  retroswan's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://retroswan.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: retro_swanny
github_username:  retroswan

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 1
paginate_path: "/blog/page:num/"

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
